### ISSUE TITLE
Are there any plans to bring that back to master in the near future?

### ISSUE THREAD

**Issue by mgiaco** [mbed-Infineon-XMC/mbed-os#20]
This isn´t a fork so I am wondering if this will go mainline one day?

**Comment by mbed-Infineon-XMC** [comment]
Hi!
What did you mean with 'bring that back to master..'? :)
Checkout the first 'stable' release v1.0

**Comment by mgiaco** [comment]
I mean bring it back to https://github.com/ARMmbed/mbed-os I am wonder why this isn´t made as a fork.

**Comment by mbed-Infineon-XMC** [comment]
This project was launched as part of a university project.
At the moment there is no contact between this repo and Infineon.
Bringing Infineon support to the main mbed-os repository can only be done with consent of Infineon.
 I try to figure out how Infineon is related to this topic. A cooperation and the migration to the main mbed-os repository would be useful.
At the moment you can find here a copy of the original mbed-os-5.7.4 release with the additional Infineon files.

**Comment by mgiaco** [comment]
I do not mean any contact to Infineon. It would be nice if you translate your changes into a pull request for the main mbed-os repository. Maybe the community will use it and then i will be maintained like other ports.

**Comment by mbed-Infineon-XMC** [comment]
Ok, I understand your point... I will put my changes into a pull request as soon as possible.

**Comment by mgiaco** [comment]
That sounds really great.
